development:
  adapter: postgresql
  encoding: unicode
  database: ats_development
  pool: 5
  username: ats
  password: ats

test:
  adapter: postgresql
  encoding: unicode
  database: ats_test
  pool: 5
  username: ats
  password: ats